;/*FB_PKG_DELIM*/

__d("CometComposerPushedPageOnLoad",[],(function(a,b,c,d,e,f){a=Object.freeze({ASK_FOR_RECOMMENDATIONS:"ask_for_recommendations",ASK_ME_ANYTHING:"ask_me_anything",CONNECT_WHATSAPP:"connect_whatsapp",FEELING:"feeling",FUNDRAISER:"fundraiser",GET_MESSAGES:"get_messages",GET_WHATSAPP_MESSAGES:"get_whatsapp_messages",LOCAL_ALERT_TAGGER:"local_alert_tagger",LOCATION_TAGGER:"location_tagger",LOOKING_FOR_PLAYERS:"looking_for_players",MLE:"mle",PHOTO_VIDEO:"photo_video",PRAYER:"prayer",PRODUCT_TAGGER:"product_tagger",QUILTS_COMPOSER:"quilts_composer",SHARE_CANDIDATE:"share_candidate",SHIFT_COVER:"shift_cover",SHIFT_MANAGEMENT_COVER:"shift_management_cover",VIDEO_MEETUP:"video_meetup",VIDEO_PICKER:"video_picker",VOTING_ALERT_TAGGER:"voting_alert_tagger",WITH_TAGGER:"with_tagger"});f["default"]=a}),66);
__d("CometComposerSwatchPickerMenuUsingRelayEntrypointQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9236602696415853"}),null);
__d("CometCreationContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({isDraft:!1});g["default"]=b}),98);
__d("useIsCreationPreview",["CometCreationContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){var a=i(c("CometCreationContext"));return a.isDraft}g["default"]=a}),98);
__d("FDSCreationPreviewPlaceholder.react",["react","useIsCreationPreview"],(function(a,b,c,d,e,f,g){"use strict";var h;h||d("react");function a(a){var b=a.children,d=a.placeholder,e=a.shouldShowPlaceholder;e=e===void 0?!1:e;var f=c("useIsCreationPreview")();a=Object.prototype.hasOwnProperty.call(a,"stringValueToCheck")&&(a.stringValueToCheck==null||a.stringValueToCheck==="");return f&&(a||e)?d:b}g["default"]=a}),98);
__d("GroupLeadersEngagementFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743660");b=d("FalcoLoggerInternal").create("group_leaders_engagement",a);e=b;g["default"]=e}),98);
__d("GroupsEntityScopedCometTypeaheadDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4958745114174592"}),null);
__d("GroupsKeyCommandShortcutsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2955");b=d("FalcoLoggerInternal").create("groups_key_command_shortcuts",a);e=b;g["default"]=e}),98);
__d("useIsFDSEntityHeaderMobile",["useMatchViewport"],(function(a,b,c,d,e,f,g){"use strict";var h=700;function a(){return c("useMatchViewport")("max","width",h)}g["default"]=a}),98);